const model = @import("model.zig");

pub const definitions = [_]model.FeatureDefinition{
    // ── Navigator (0-5) ─────────────────────────────────────────────
    .{
        .id = .UserAgent,
        .category = .Navigator,
        .value_type = .String,
        .weight = 90,
        .flags = .critical,
        .name = "User Agent",
        .description = "Browser user agent string.",
    },
    .{
        .id = .Language,
        .category = .Navigator,
        .value_type = .String,
        .weight = 40,
        .flags = .stable_required,
        .name = "Language",
        .description = "Primary browser language.",
    },
    .{
        .id = .Languages,
        .category = .Navigator,
        .value_type = .StringArray,
        .weight = 50,
        .flags = .stable_required,
        .name = "Languages",
        .description = "Preferred browser languages.",
    },
    .{
        .id = .Platform,
        .category = .Platform,
        .value_type = .String,
        .weight = 70,
        .flags = .stable_required,
        .name = "Platform",
        .description = "Browser platform identifier.",
    },
    .{
        .id = .Vendor,
        .category = .Navigator,
        .value_type = .String,
        .weight = 30,
        .flags = .stable_required,
        .name = "Vendor",
        .description = "Browser vendor string.",
    },
    .{
        .id = .CookieEnabled,
        .category = .Navigator,
        .value_type = .Boolean,
        .weight = 20,
        .flags = .stable_required,
        .name = "Cookie Enabled",
        .description = "Whether cookies are enabled in the browser.",
    },

    // ── Hardware (6-7) ──────────────────────────────────────────────
    .{
        .id = .HardwareConcurrency,
        .category = .Hardware,
        .value_type = .Integer,
        .weight = 50,
        .flags = .stable_entropy,
        .name = "Hardware Concurrency",
        .description = "Number of logical CPU cores available.",
    },
    .{
        .id = .DeviceMemory,
        .category = .Hardware,
        .value_type = .Float,
        .weight = 40,
        .flags = .stable_entropy,
        .name = "Device Memory",
        .description = "Approximate device RAM in gigabytes.",
    },

    // ── Screen (8-14) ───────────────────────────────────────────────
    .{
        .id = .ScreenWidth,
        .category = .Screen,
        .value_type = .Integer,
        .weight = 60,
        .flags = .stable_required,
        .name = "Screen Width",
        .description = "Primary screen width.",
    },
    .{
        .id = .ScreenHeight,
        .category = .Screen,
        .value_type = .Integer,
        .weight = 60,
        .flags = .stable_required,
        .name = "Screen Height",
        .description = "Primary screen height.",
    },
    .{
        .id = .AvailableWidth,
        .category = .Screen,
        .value_type = .Integer,
        .weight = 50,
        .flags = .stable_required,
        .name = "Available Width",
        .description = "Available screen width excluding taskbars.",
    },
    .{
        .id = .AvailableHeight,
        .category = .Screen,
        .value_type = .Integer,
        .weight = 50,
        .flags = .stable_required,
        .name = "Available Height",
        .description = "Available screen height excluding taskbars.",
    },
    .{
        .id = .ColorDepth,
        .category = .Screen,
        .value_type = .Integer,
        .weight = 35,
        .flags = .stable_required,
        .name = "Color Depth",
        .description = "Screen color depth in bits.",
    },
    .{
        .id = .PixelDepth,
        .category = .Screen,
        .value_type = .Integer,
        .weight = 35,
        .flags = .stable_required,
        .name = "Pixel Depth",
        .description = "Screen pixel depth in bits.",
    },
    .{
        .id = .DevicePixelRatio,
        .category = .Screen,
        .value_type = .Float,
        .weight = 45,
        .flags = .stable_required,
        .name = "Device Pixel Ratio",
        .description = "Browser device pixel ratio.",
    },

    // ── Canvas (15) ──────────────────────────────────────────────────
    .{
        .id = .CanvasHash,
        .category = .Canvas,
        .value_type = .Bytes,
        .weight = 100,
        .flags = .critical,
        .name = "Canvas Hash",
        .description = "SHA-256 hash of rendered canvas.",
    },

    // ── WebGL (16-19) ────────────────────────────────────────────────
    .{
        .id = .WebGLVendor,
        .category = .WebGL,
        .value_type = .String,
        .weight = 80,
        .flags = .stable_entropy,
        .name = "WebGL Vendor",
        .description = "WebGL vendor string.",
    },
    .{
        .id = .WebGLRenderer,
        .category = .WebGL,
        .value_type = .String,
        .weight = 90,
        .flags = .critical,
        .name = "WebGL Renderer",
        .description = "GPU renderer string.",
    },
    .{
        .id = .WebGLVersion,
        .category = .WebGL,
        .value_type = .String,
        .weight = 60,
        .flags = .stable_entropy,
        .name = "WebGL Version",
        .description = "WebGL version string.",
    },
    .{
        .id = .WebGLHash,
        .category = .WebGL,
        .value_type = .Bytes,
        .weight = 100,
        .flags = .critical,
        .name = "WebGL Hash",
        .description = "Hashed WebGL fingerprint.",
    },

    // ── Audio & Fonts (20-21) ────────────────────────────────────────
    .{
        .id = .AudioHash,
        .category = .Audio,
        .value_type = .Bytes,
        .weight = 95,
        .flags = .critical,
        .name = "Audio Hash",
        .description = "Hash of rendered audio fingerprint.",
    },
    .{
        .id = .FontsHash,
        .category = .Fonts,
        .value_type = .Bytes,
        .weight = 95,
        .flags = .critical,
        .name = "Fonts Hash",
        .description = "Hash of installed fonts fingerprint.",
    },

    // ── Hardware & Platform (22-23) ──────────────────────────────────
    .{
        .id = .CpuClass,
        .category = .Hardware,
        .value_type = .String,
        .weight = 40,
        .flags = .stable_entropy,
        .name = "CPU Class",
        .description = "Browser CPU architecture class.",
    },
    .{
        .id = .OperatingSystem,
        .category = .Platform,
        .value_type = .String,
        .weight = 75,
        .flags = .stable_required,
        .name = "Operating System",
        .description = "Operating system identifier.",
    },

    // ── Storage (24-26) ──────────────────────────────────────────────
    .{
        .id = .LocalStorage,
        .category = .Storage,
        .value_type = .Boolean,
        .weight = 30,
        .flags = .stable_required,
        .name = "Local Storage",
        .description = "Whether localStorage is available.",
    },
    .{
        .id = .SessionStorage,
        .category = .Storage,
        .value_type = .Boolean,
        .weight = 25,
        .flags = .stable_required,
        .name = "Session Storage",
        .description = "Whether sessionStorage is available.",
    },
    .{
        .id = .IndexedDB,
        .category = .Storage,
        .value_type = .Boolean,
        .weight = 25,
        .flags = .stable_required,
        .name = "IndexedDB",
        .description = "Whether IndexedDB is available.",
    },

    // ── Permissions (27) ─────────────────────────────────────────────
    .{
        .id = .NotificationPermission,
        .category = .Permissions,
        .value_type = .String,
        .weight = 20,
        .flags = .stable_required,
        .name = "Notification Permission",
        .description = "Notification permission status.",
    },

    // ── Media (28-30) ────────────────────────────────────────────────
    .{
        .id = .AudioInputDevices,
        .category = .Media,
        .value_type = .StringArray,
        .weight = 30,
        .flags = .{ .stable = true },
        .name = "Audio Input Devices",
        .description = "Available audio input device labels.",
    },
    .{
        .id = .AudioOutputDevices,
        .category = .Media,
        .value_type = .StringArray,
        .weight = 25,
        .flags = .{ .stable = true },
        .name = "Audio Output Devices",
        .description = "Available audio output device labels.",
    },
    .{
        .id = .VideoInputDevices,
        .category = .Media,
        .value_type = .StringArray,
        .weight = 30,
        .flags = .{ .stable = true },
        .name = "Video Input Devices",
        .description = "Available video input device labels.",
    },

    // ── Network (31) ─────────────────────────────────────────────────
    .{
        .id = .ConnectionType,
        .category = .Network,
        .value_type = .String,
        .weight = 45,
        .flags = .{ .stable = true },
        .name = "Connection Type",
        .description = "Network connection type (e.g. bluetooth, cellular).",
    },

    // ── Locale & Timezone (32-33) ────────────────────────────────────
    .{
        .id = .Locale,
        .category = .Locale,
        .value_type = .String,
        .weight = 35,
        .flags = .stable_required,
        .name = "Locale",
        .description = "Browser locale string.",
    },
    .{
        .id = .Timezone,
        .category = .Timezone,
        .value_type = .String,
        .weight = 40,
        .flags = .stable_required,
        .name = "Timezone",
        .description = "IANA timezone identifier.",
    },

    // ── Metadata (34-36) ─────────────────────────────────────────────
    .{
        .id = .SchemaVersion,
        .category = .Metadata,
        .value_type = .Integer,
        .weight = 0,
        .flags = .required_entropy,
        .name = "Schema Version",
        .description = "Fingerprint schema version number.",
    },
    .{
        .id = .SDKVersion,
        .category = .Metadata,
        .value_type = .String,
        .weight = 0,
        .flags = .required_entropy,
        .name = "SDK Version",
        .description = "Fingerprint SDK version string.",
    },
    .{
        .id = .CollectionTimestamp,
        .category = .Metadata,
        .value_type = .Integer,
        .weight = 0,
        .flags = .required_entropy,
        .name = "Collection Timestamp",
        .description = "Unix timestamp of fingerprint collection.",
    },
};
